# Generated by Django 3.0.7 on 2020-06-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='division',
            field=models.CharField(choices=[('', 'Select'), ('HSE', 'HSE'), ('Keuangan', 'Keuangan'), ('Manajemen Direksi', 'Manajemen Direksi'), ('Lapangan', 'Lapangan')], max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('', 'Select'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=50),
        ),
    ]
