# Generated by Django 3.0.7 on 2020-06-24 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_item_picture'),
        ('employee', '0002_auto_20200623_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='employee_nik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='borrowtransaction',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.Item'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='division',
            field=models.CharField(choices=[('Lapangan', 'Lapangan'), ('Keuangan', 'Keuangan'), ('HSE', 'HSE'), ('Manajemen Direksi', 'Manajemen Direksi'), ('', 'Select')], max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('', 'Select')], default='', max_length=50),
        ),
    ]
