# Generated by Django 3.0.7 on 2020-06-30 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200624_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowtransaction',
            name='project_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='division',
            field=models.CharField(choices=[('HSE', 'HSE'), ('Manajemen Direksi', 'Manajemen Direksi'), ('Lapangan', 'Lapangan'), ('', 'Select'), ('Keuangan', 'Keuangan')], max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('', 'Select'), ('Male', 'Male')], default='', max_length=50),
        ),
    ]
