# Generated by Django 3.0.7 on 2020-06-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_picture',
        ),
    ]
