# Generated by Django 3.0.7 on 2020-06-25 14:57

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_itemhistoryservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemhistoryservice',
            name='item_history_service_id',
            field=models.CharField(default=items.models.ItemHistoryService.increment_service_number, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
