# Generated by Django 3.0.7 on 2020-06-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20200625_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemhistoryservice',
            name='picture',
            field=models.ImageField(blank=True, default='album_history/no-image.jpg', upload_to='album_history'),
        ),
    ]
