# Generated by Django 3.0.7 on 2020-06-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_itemhistoryservice_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_picture',
            field=models.ImageField(blank=True, default='album_item/no-image.jpg', upload_to='album_item/'),
        ),
        migrations.AlterField(
            model_name='itemhistoryservice',
            name='picture',
            field=models.ImageField(blank=True, default='album_history/no-image.jpg', upload_to='album_history/'),
        ),
    ]
