# Generated by Django 3.0.7 on 2020-06-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20200626_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Active or not'),
        ),
    ]
